### ISSUE TITLE
Ability to switch between CDMv4 and v5 (at start of application)

### ISSUE THREAD

**Issue by schuemie** [OHDSI/WhiteRabbit#12]

**Comment by aguynamedryan** [comment]
@schuemie, the completion of #44 is would satisfy this issue as well, yes?

**Comment by schuemie** [comment]
@aguynamedryan, I was thinking that CDMv4 and v5 would be baked into the program (maybe an option in the menu?). The sandbox CDMs would be custom definitions that someone would load from an external file, right?

So, in other words, users could choose between 3 options (currently):
 1. CDM v4
 2. CDM v5
 3. Custom (load from file)

**Comment by aguynamedryan** [comment]
Here's the way this feature works at the moment.  We'll do more work on this to complete #44.

![cdmswitch](https://cloud.githubusercontent.com/assets/117722/8016952/cf30d124-0b9f-11e5-8722-abde76314737.gif)

**Comment by aguynamedryan** [comment]
We're still working on #44, but @marc-outins has made it so that when you switch between CDM versions, any mappings that share identical combinations of table and column name will be carried over. This is not perfect, for instance, CDMv4 preferred table.associated_provider_id vs CDMv5's table.provider_id, so those mappings get lost, as do others, I imagine, but it's better than nothing and should be very helpful if we migrate an existing CDMv5 spec to a sandbox CDM spec.

![changecdm](https://cloud.githubusercontent.com/assets/117722/8042183/4cb3daf4-0dd2-11e5-83ba-f624b932593f.gif)
