### ISSUE TITLE
Connection error in Oracle 12c version

### ISSUE THREAD

**Issue by mircom2** [OHDSI/WhiteRabbit#125]
![image](https://cloud.githubusercontent.com/assets/27811302/25879785/8f439588-356e-11e7-99ec-c8709b609d63.png)

If you know how to solve this problem, I would appreciate your help.

**Comment by schuemie** [comment]
Could you provide some information on how you're trying to connect? Is the database accessible through a THIN interface?

This error message is saying it tried THIN but failed, and then tried to fall back to OCI (which isn't tested very thoroughly because I don't have an OCI interface up and running). Most likely there is simply something wrong with the OCI connection details.

**Comment by mircom2** [comment]
I have resolved the issue by copying the ojdbc7 driver to the WhiteRabbit_lib folder and retrying the connection.

Thank you schuemie.

**Comment by schuemie** [comment]
Thanks @mircom2 ! I will make sure to add ojdbc7 to WhiteRabbit in the next release.

**Comment by chPark5667** [comment]
> ![image](https://cloud.githubusercontent.com/assets/27811302/25879785/8f439588-356e-11e7-99ec-c8709b609d63.png)
> 
> 어떻게 이 문제를 해결하셨는지 도움이 필요합니다. ojdbc7을 lib폴더에 넣고 
코딩 수정같은 다른 작업은 실시하지 않은셨나요??
