### ISSUE TITLE
Arithmetic Overflow Error When Connecting to Parallel Data Warehouse

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/WhiteRabbit#128]
I am attempting to scan a database on PDW and I am getting this error

> Jun 6, 2017 11:14:08 AM	Scanning table MEDICAL_CLAIMS
SELECT COUNT(*) FROM MEDICAL_CLAIMS
Arithmetic overflow error converting expression to data type int.
Error: java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Arithmetic overflow error converting expression to data type int.
Error: java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Arithmetic overflow error converting expression to data type int.
An error report has been generated:

**Comment by pbr6cornell** [comment]
COUNT_BIG(*) should work

**Comment by schuemie** [comment]
I've switched to COUNT_BIG in [the latest release](https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.5.21). Note that I've added PDW as it's own platform, and the analysis of field values should now work on PDW (didn't work before because PDW doesn't support [TABLESAMPLE](https://technet.microsoft.com/en-us/library/ms189108(v=sql.105).aspx).

@clairblacketer, could you test and let me know if it works?

**Comment by clairblacketer** [comment]
@schuemie It worked! Thank you so much for the fix!
