### ISSUE TITLE
Could not connect to DB : Unable to retrieve table names for database sid(oracle DB)

### ISSUE THREAD

**Issue by roc-lee** [OHDSI/WhiteRabbit#136]
hello,It's ERROR is  this title , and sorry to picture Upload was not successful

-

**Comment by schuemie** [comment]
This is an interesting message, because it suggests you were able to connect to the server, but retrieving table names failed. 

Can you confirm that the name of your database (better known as the 'user name' for Oracle users) is really 'sid'?

Are there any tables in the sid database?

This is the SQL that WhiteRabbit is trying to execute. Are you able to run it yourself in a SQL client?

```sql
SELECT table_name FROM all_tables WHERE owner='SID';
```

**Comment by roc-lee** [comment]
i solve this issue; because config Interface “Database name” is not sid or server name ,it is should username
