### ISSUE TITLE
Unable to generate document

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/WhiteRabbit#155]
Using the most recent release I am unable to generate an ETL document; when I click the option the hourglass comes up but the process hangs. This is also happening with older versions so it is possible it is a problem with my specs, though I totally regenerated them through the tool and it is still happening. Any help would be appreciated.

This is the exception I'm getting:
![image](https://user-images.githubusercontent.com/12911960/58269774-39afe900-7d56-11e9-8ea1-f4f5b66b803b.png)

I think it has to do with v6.0 :( since I don't get the error when I try to generate a v5.3.1 document.

**Comment by schuemie** [comment]
The reason for this is an illegal mapping in your specs file, caused by this issue:

The stem default mapping for CDM v5.3.1 includes mappings from [qualifier_concept_id](https://github.com/OHDSI/WhiteRabbit/blob/master/rabbitinahat/src/main/resources/org/ohdsi/rabbitInAHat/dataModel/StemTableDefaultMappingV5.3.1.csv#L79) and [qualifier_source_value](https://github.com/OHDSI/WhiteRabbit/blob/master/rabbitinahat/src/main/resources/org/ohdsi/rabbitInAHat/dataModel/StemTableDefaultMappingV5.3.1.csv#L86), but these fields are not in the [stem table v5.3.1 specs](https://github.com/OHDSI/WhiteRabbit/blob/master/rabbitinahat/src/main/resources/org/ohdsi/rabbitInAHat/dataModel/StemTableV5.3.1.csv). 

You're the best person to ask this question ;-) were these fields already part of the CDM v5.3.1 observation table specs? If so, I'll need to add them to the stem table specs. If not, I'll delete the mappings.

**Comment by clairblacketer** [comment]
Hi @schuemie the qualifier_concept_id and qualifier_source_value were part of CDM v5.3.1 and they should be added to the stem table specs. 

Thank you for digging into this for me!
