### ISSUE TITLE
Reduce Java VM memory allocation for WhiteRabbit

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/WhiteRabbit#241]
With the default setting, the system tries to allocate 2400 mb of memory for WhiteRabbit. For many systems this is too much and WhiteRabbit will not start. 
This setting should be either easily configurable or reduced.

**Comment by blootsvoets** [comment]
This is maximum memory though. If the memory is not used, it will not be allocated to that level. It looks like this was changed in the PR for BigQuery support. Perhaps a lot of memory is needed for that?

Does setting environment variable `EXTRA_JVM_ARGUMENTS=-Xmx1200m` before starting the script help?

Otherwise the BAT and SH scripts would probably have to be customized to read arguments (or env variables) from a file.

**Comment by MaximMoinat** [comment]
Issue could also be due to Java 32 vs 64 bit, see the resolution to #255:
> On my 64GB Win 10 computer, the error message is "java Error occurred during initialization of VM. Could not reserve enough space for 2457600KB object heap." The problem was that I had a 32-bit version of Java installed, which is the default download option. (Adding "-d64" to the whiterabbit.bat's java command, %JAVACMD% %JAVA_OPTS% -Xmx2400m -d64 ..., showed the problem.) **Uninstalling 32-bit Java and installing 64-bit Java resolved the error.**
