### ISSUE TITLE
When I installed latest version and double click on bin/whiteRabbit for windows, it does not open up

### ISSUE THREAD

**Issue by poonamyadav08** [OHDSI/WhiteRabbit#255]

**Comment by MaximMoinat** [comment]
This is a known issue. See also this thread: #220  
Two things you can try:
1. Check security settings, it could be that Windows Defender blocks the app
2. Move the whole package (the `dist` folder) to your root drive (e.g. `C://`). Try opening it there.

If this does not work, try to run WhiteRabbit[ from the command line](http://ohdsi.github.io/WhiteRabbit/WhiteRabbit.html#running_from_the_command_line). This should show the error message that prevents WhiteRabbit from launching.

**Comment by rfurmanimd** [comment]
On my 64GB Win 10 computer, the error message is "java Error occurred during initialization of VM. Could not reserve enough space for 2457600KB object heap." The problem was that I had a 32-bit version of Java installed, which is the default download option. (Adding "-d64" to the whiterabbit.bat's java command, %JAVACMD% %JAVA_OPTS% -Xmx2400m -d64 ..., showed the problem.) Uninstalling 32-bit Java and installing 64-bit Java resolved the error.

**Comment by MaximMoinat** [comment]
Thanks for the update, glad you found the issue. Will close this issue now.

Tagging in issue #241
