### ISSUE TITLE
Add `count distinct` to scan report

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/WhiteRabbit#300]
It would be nice if WhiteRabbit would count the number of distinct values in a column. Tagging @fdefalco

**Comment by MaximMoinat** [comment]
This has been implemented since version 0.9.0. 'N unique values', see https://github.com/OHDSI/WhiteRabbit/pull/150 .
This was actually trickier than it seems. WhiteRabbit will nog keep all values in memory if the source table contains too many records. So if there are a lot of unique values, this will be just an upper bound.

**Comment by clairblacketer** [comment]
thanks @MaximMoinat!
