### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by iei-fa** [OHDSI/WhiteRabbit#301]
I followed the installation instructions but after all I got the following screen.
![controlpanel](https://user-images.githubusercontent.com/83918983/117580617-728f2700-b101-11eb-8573-ff10bb2443a4.png)

Any help and suggestions?
Ivan

**Comment by MaximMoinat** [comment]
Great to read your problem is solved and good to know that paths only work with ascii characters.

**Comment by blootsvoets** [comment]
Note: it might be that this problem would be solved by using a later version of the maven Appassembler plugin. In any case, this but will be caused by https://github.com/mojohaus/appassembler, perhaps a quoting issue like https://github.com/mojohaus/appassembler/issues/114 or https://github.com/mojohaus/appassembler/issues/85.
