### ISSUE TITLE
Invalid File Format

### ISSUE THREAD

**Issue by SofiaMp** [OHDSI/WhiteRabbit#316]
When trying to `open scan report` of a newly generated scan report RiaH gives error `Invalid File Format`. However works when opening older scan reports.

Steps followed:
1. Use White Rabbit to generate a scan report of a few Synthea tables, reading from csv files
2. Open scan report generated with RiaH

Working with WhiteRabbit_v0.10.4 on MacOS 11.5.2
Both old and new scan report have extension `.xlsx` and don't appear to have any visual differences.

**Comment by MaximMoinat** [comment]
The issue also happens in v0.10.5.

The error happens when RiaH tries to get the first sheet from the scan report (line 150). It fails to get the overview sheet either by name or by position. It seems like the xlsx reader cannot retrieve any sheets from the workbook.
https://github.com/OHDSI/WhiteRabbit/blob/be4dbd2e522a7c9b2b252c80e6d15f1a253c3561/rabbit-core/src/main/java/org/ohdsi/rabbitInAHat/dataModel/Database.java#L147-L151

**Comment by ChanchalDixit-Cognizant** [comment]
Hello,

Can you please let me know if this is resolved. Need to use this.
Thanks.

**Comment by PYDuquesnoy** [comment]
As a workaround, you can open the ScanReport.xlsx in Excel, and save it. After this operation, rabbitInaHat can process the file correctly.

**Comment by ChanchalDixit-Cognizant** [comment]
Wow, It worked. Thank you @PYDuquesnoy .

**Comment by MaximMoinat** [comment]
Thanks @PYDuquesnoy for providing this workaround. We are looking into the issue at the moment.

**Comment by MaximMoinat** [comment]
Initial inspection shows that somehow the scanreport produced with release v0.10.4 and v0.10.5, cannot be read in correctly by the excel reader. The xml files are somehow not found. This seems to be an issue with the writing of Excel files with the new apache poi dependencies.
