### ISSUE TITLE
[Suggested Feature] Indicate which mappings (represented by arrows) have no information

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/WhiteRabbit#35]
It would be nice to be able to tell, at a glance, which column mappings have no comments or logic filled out. At the table-level view, a table would be considered “incomplete” if it contains any “incomplete” column mappings. That way, as I’m looking over the entire ETL, I can see what work is still left to be done.

Tentatively we could render just the outline of the arrows in a thick border, leaving the center of the arrow “hollow”. Or we can color the arrows yellow?

**Comment by claire-oi** [comment]
We've workshopped this feature internally a bit and come up with the following approach:

Instead of showing "incomplete" arrows in a different color or making them "hollow", we will instead simply hide "completed" arrows.  A field-level arrow is "complete" if it meets any of the following three criteria :
- has text in the comment field
- has text in the logic field
- has been manually marked "completed"

A  table-level arrow is considered complete if it meets either of the two following criteria:
- has all associated field-level arrows are "complete"
- has been manually marked "completed"

Users will be able to toggle between showing/hiding completed arrows using a toggle button in a drop down menu.

When the user opt to hid completed arrows, we'll somehow indicate that completed arrows are hidden, either by changing the background color of the mapping panel, or displaying something like "hiding completed" at the top of each mapping panel.

As alluded to above, we'll include a new checkbox in the details panel for each mapping.  If a user checks that box, the mapping will be considered complete, even if there is no text in either the logic or comment boxes.  We're adding this checkbox to facilitate situations where there might be, say, 43 HCPCS-related fields that all share the same logic and comments when mapped to the procedure_source_value and we only want to fill out the logic and comment section for the first HCPCS -> procedure_source_value field and leave the rest completely empty.  We still need to be able to mark the rest of the HCPCS fields as "complete".  Since we'll want to quickly mark those 42 other HCPCS codes as completed, we'll provide an option to mark a set of selected arrows as completed/not-completed en-mass using some drop down menu items.

Lastly, when a user hides completed arrows, they might attempt to redraw an arrow that already exists, but has been hidden.  Perhaps we need to throw up a warning when the user attempts to redraw an existing arrow and give them the option to turn hiding off.

**Comment by schuemie** [comment]
How about drastically increasing the transparency of completed arrows and make it impossible to select them? So they'd be 'ghosts', reminding people that they're there.

**Comment by claire-oi** [comment]
@schumie, we think your suggestion may be a more straight-forward solution. We will test it internally and throw up some screen shots to see if we all like how it turns out.

**Comment by aguynamedryan** [comment]
We're working out a few bugs and still need to implement the "completed" check box, but here's how the UI looks based on @schuemie's suggestions:

![hidecompleted](https://cloud.githubusercontent.com/assets/117722/8041205/63ee91f2-0dcb-11e5-9427-19e12fc4075a.gif)

- Users can toggle "hiding" completed items on and off
- Completed items are drawn with very high transparency
  - Users can still select completed arrows
- We added a mint-green color to the selected arrow

**Comment by aguynamedryan** [comment]
@chrisknoll suggested requiring users to manually mark mappings as complete.

This is definitely a far simpler approach and I like it.  So now, if a user wants to mark a mapping as complete, they will need to do so by selecting "Mark Highlighted Arrow Complete" from the Arrows menu or using CTRL-D for "Done" ;-)

Since we're having users manually control completion of mappings, I'm also going to be so bold as to remove the option to turn off dimming down the arrows.  What I'm saying RiaH will always show "complete" arrows as dim arrows and a user may simply opt to never mark arrows as complete if they want to keep all of the arrows nice and dark.

Simplify, simplify, simplify.

**Comment by aguynamedryan** [comment]
Closed by #85
