### ISSUE TITLE
NullPointerException when trying to scan with WhiteRabbit

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/WhiteRabbit#94]
Richard Starr [reported a NullPointerException in the forums](http://forums.ohdsi.org/t/whiterabbit-rabbitinahat-v0-5-0-mac-os/639/3) when trying to scan with WhiteRabbit under release 0.5.0

When I went to try scanning on my copy of WhiteRabbit, I too got a [FileNotFound exception](https://gist.github.com/507a196bdadad227cacc) in my debugger and the WhiteRabbit looked like this:
![image](https://cloud.githubusercontent.com/assets/117722/8315065/ad6ed0e8-19a2-11e5-8722-1373a85fe530.png)

[Here's your problem](https://github.com/OHDSI/WhiteRabbit/blob/master/src/org/ohdsi/whiteRabbit/WhiteRabbitMain.java#L529) -- a Mac doesn't have a C: drive!

I'm not _exactly_ sure what the proper fix is here, other than removing that line of code?  When I comment that line out and run scan, it runs to completion.

**Comment by aguynamedryan** [comment]
Correction, WhiteRabbit looks like this:
![image](https://cloud.githubusercontent.com/assets/117722/8315226/ee188c46-19a3-11e5-9838-d3dbb173ab28.png)

**Comment by taylordelehanty** [comment]
Hi @aguynamedryan , so WhiteRabbit-v0.5.0 isn't upgraded with your modification here? Because I'm still getting that NullPointerException (but mine is in Thread-1). So then I tried to clone your version and re-compile it so I could update the .jar files in the WhiteRabbit-v0.5.0 directory that I got from the Releases tab, but it won't recompile because it doesn't recognize the packages. How would I go about getting your version to run?

**Comment by aguynamedryan** [comment]
@taylordelehanty, when you say you can't recompile, I'll need more detail than that to provide guidance.  For instance, please include a link to a gist with the error messages you're getting, or a screen shot of the errors.

Here's a quick gif showing how I'd build the custom version on my Mac.  Your mileage may vary depending on how your environment is setup.

![buildcustomwhiterabbit](https://cloud.githubusercontent.com/assets/117722/8367776/b04917be-1b56-11e5-982c-681c755942d0.gif)

@schuemie, would you be able to release v0.5.1 soon after approving this pull request?

**Comment by taylordelehanty** [comment]
Thanks for your response! I haven't tried the way you just showed me, but I will right after I send this.
Up to now, I've cloned WhiteRabbit and made the alteration you suggested to WhiteRabbitMain.java in jGrasp (because it has a java compiler in the IDE) but when I tried to compile it, I got a lot of errors, most of them pertaining to the SourceDataScan.java file:

![sourcedatascanerror](https://cloud.githubusercontent.com/assets/10815130/8384794/cc024e4e-1c00-11e5-83bc-9efb8c840c13.png)


![failedcompilation](https://cloud.githubusercontent.com/assets/10815130/8384691/1c3c0284-1c00-11e5-84c6-aab564b4d816.png)

**Comment by taylordelehanty** [comment]
I just followed the step you highlighted in your .gif and they worked like a charm! Thanks @aguynamedryan.
I don't really know why compiling it all like I tried to do wouldn't work; would you or anyone else know why that is?

**Comment by aguynamedryan** [comment]
@taylordelehanty, glad to hear it's working for you!

I can't answer your compilation questions as I'm fairly new to the [ant build system](https://ant.apache.org/) that WhiteRabbit employs. 

Maybe @schuemie or another member of the OHDSI community can shed some light on what's going on.

**Comment by taylordelehanty** [comment]
Yeah, I noticed the use of ant, and I also don't know a lot about it! I might explore more about it because it seems extremely useful if it can create the .jar files for both WR and RIAH with one command.
Thanks again for your help!

**Comment by schuemie** [comment]
So sorry about that, and thanks @aguynamedryan for fixing this! I published a new version with the bug fix.
